name: "ONVIF PTZ Stabiliser"
version: "1.0.14"
slug: "onvif_ptz_stabiliser"
description: "Monitors and stops PTZ movement after stabilisation for multiple cameras"
url: "https://github.com/jumpinf00l/dev_onvif_ptz_stabiliser"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: services
boot: auto
panel_icon: mdi:camera-control
panel_admin: true
backup: cold
options:
  log_level: "INFO"
schema:
  log_level: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)
  cameras:
    - camera_name: str
      host: str
      port: port
      username: str
      password: password
      ignore_ssl: bool?
      reconnect_time: float?
      polling_interval: float?
      fast_poll_on_move: bool?
