name: "ONVIF PTZ Stabiliser"
version: "1.0.10"
slug: "onvif_ptz_stabiliser"
description: "Monitors and stops PTZ movement after stabilisation for multiple cameras"
url: "https://github.com/jumpinf00l/dev_onvif_ptz_stabiliser"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: services
boot: auto
options:
  min_log_level: "INFO"
  cameras:
    ignore_ssl: false
    reconnect_time: 5
    polling_interval: 0.3
    fast_poll_on_move: false
schema:
  min_log_level: str
  cameras:
      - name: str
        ip_address: str
        port: int
        username: str
        password: str
        ignore_ssl: bool
        reconnect_time: int
        polling_interval: float
        fast_poll_on_move: bool

