name: "ONVIF PTZ Stabiliser"
version: "1.0.0"
slug: "onvif_ptz_stabiliser"
description: "Monitors and stops PTZ movement after stabilization for multiple cameras"
url: "https://github.com/yourusername/your-repo-name"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
options:
  min_log_level: "INFO"
  cameras: []
schema:
  min_log_level: str
  cameras:
    - name:
        name: str
        ip_address: str
        port: int
        username: str
        password: str
        ignore_ssl: bool
        reconnect_time: int
        polling_interval: float
        fast_poll_on_move: bool
