name: "ONVIF PTZ Helper"
version: "2026.2.1"
slug: "onvif_ptz_helper"
description: "Helps some ONVIF cameras (e.g. Hikvision) which do not reliably update PTZ status to allow Frigate Autotracking to work"
url: "https://github.com/jumpinf00l/dev_onvif_ptz_stabiliser"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: services
boot: auto
panel_icon: mdi:camera-control
backup: cold
options:
  log_level: "INFO"
  cameras: []
schema:
  log_level: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)
  cameras:
    - camera_name: str
      host: str
      port: port
      username: str
      password: password
      ignore_ssl: bool?
      reconnect_time: float?
      polling_interval: float?
      fast_poll_on_move: bool?
